platform :ios, '12.2'
use_frameworks!

target 'TalkVeganToMe' do
  #pod 'Amplitude-iOS', '~> 4.3.1'

  #pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'

  #pod 'react-native-amplitude-analytics', :path => '../node_modules/react-native-amplitude-analytics'
  #pod 'Amplitude-iOS', '~> 4.3.1'
  pod 'Amplitude-iOS', '~> 4.3.1'
  #pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNRate', :path => '../node_modules/react-native-rate'

  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

end
