platform :ios, '12.2'
use_frameworks!

target 'TalkVeganToMe' do
  pod 'Amplitude-iOS', '~> 4.5'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'

end
