# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    #sh('echo $PWD || false')
    sh("find ../app/build/outputs/apk/ -name \\*.apk -exec rm {} \\;")
    android_set_version_code(
      version_code: "27"
    )
    android_set_version_name(
      version_name: "0.0.6"
    )
    gradle(
      task: "assemble",
      build_type: "Release",
      print_command: false,
      
      properties: {
        "android.injected.signing.store.file" => ENV["ANDROID_KEYSTORE_FILE"],
        "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_KEYSTORE_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_KEYSTORE_KEY_PASSWORD"],
      }
    )
    upload_to_play_store(track: 'internal')
  end
end
